apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    app: {{ include "django-app.name" . }}
    chart: {{ include "django-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
